### ISSUE TITLE
Many php files seem to be missing after composer install. 

### ISSUE THREAD

**Issue by pwayner** [AcroMedia/commerce-install#11]
When I run ``composer install`` on the ``composer.json``, I get a ``web`` directory that is missing the standard .php files like ``index.php`` or ``update.php``. All I see are these three directories:

core/  modules/  profiles/  sites/  themes/

**Comment by joshmiller83** [comment]
I'm seeing the same thing here, investigating.

**Comment by joshmiller83** [comment]
It's related to this: https://github.com/drupal-composer/drupal-project/issues/282

A very quick fix that worked for me:

`$ composer drupal-scaffold`

Running the above command added in all the missing files. I've now since updated from an older composer (1.4.2) to the latest (1.6.x) and am running `composer install` brings in all files.

**Comment by aanjaneyam** [comment]
I am seeing this issue with the latest composer version 1.8.5. 
I have to run 
`composer create-project drupal-composer/drupal-project some-dir --no-dev --no-interaction` 

and then run `composer drupal-scaffold` after the composer create-project command finishes to get the scaffold files (like index.php, update.php etc). 

It is the same problem even if you give a version to create-project command like 8.7.1. I have tried it with varbase too. However, somehow it works when I use `composer create-project vardot/varbase-project:8.6.x-dev ...` but not with stable version like 8.6.11 or 8.6.10 or using composer create-project command without any version in order to get the latest stable version.
